services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5157:5157"
    environment:
      DATABASE_URL: "postgresql://dev:tT8s758l79WDINR8tKHtfKBr1oiWXpWY@dpg-cr7ervi3esus7388bamg-a.frankfurt-postgres.render.com/dev_db_satsquare"
      NEXTAUTH_SECRET: "CP912ECDSClsdezoPDZCMSJXCPISJCIY20SmfdsFOYDflHZORdsvdsFOZIRGOIZHGOURHZ"
      NEXT_PUBLIC_SITE_URL: "http://app:3000"
      NEXT_PUBLIC_SOCKET_URL: "ws://app:5157"
    depends_on:
      - adminer

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "dpg-cr7ervi3esus7388bamg-a.frankfurt-postgres.render.com"
