# Dockerfile.dev
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Install development dependencies
RUN npm install --only=development

# Set environment variables for development
ENV NODE_ENV=development

# Expose ports for Next.js and WebSocket
EXPOSE 3000 5157

# Start the development server
CMD ["npm", "run", "all-dev"]
