version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - NEXTAUTH_SECRET=your-nextauth-secret
      - NEXT_PUBLIC_SITE_URL=http://nextjs:3000
      - NEXT_PUBLIC_SOCKET_URL=http://nextjs:5157

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=yourpassword
      POSTGRES_DB=sat_square_db
      POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
