services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5157:5157"
    environment:
      DATABASE_URL: "postgresql://satsquare_z45c_user:oFMPADTGdqmKobe4AEeJA1c0t549yVZ3@dpg-cr6ndeaj1k6c73d7ae90-a.frankfurt-postgres.render.com/satsquare_z45c"
      NEXTAUTH_SECRET: "CP912ECDSClsdezoPDZCMSJXCPISJCIY20SmfdsFOYDflHZORdsvdsFOZIRGOIZHGOURHZ"
      NEXT_PUBLIC_SITE_URL: "http://app:3000"
      NEXT_PUBLIC_SOCKET_URL: "ws://app:5157"
    depends_on:
      - adminer

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "dpg-coqtmei0si5c7398hrl0-a.frankfurt-postgres.render.com"
