# Dockerfile.prod
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variables for production
ENV NODE_ENV=production

# Build the Next.js application
RUN npm run build

# Expose ports for Next.js and WebSocket
EXPOSE 3000 5157

# Start the application in production mode
CMD ["npm", "run", "all"]
