version: '3'

services:
  # Commenter Nextjs si vous souhaitez developer avec Prostgres en local
  nextjs:
    build: .
    ports:
      - '3000:3000'
      - '5157:5157'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://satsquare_user:satsquare_password@db:5432/satsquare_db
      - NEXTAUTH_SECRET="CP912ECDSClsdezoPDZCMSJXCPISJCIY20SmfdsFOYDflHZORdsvdsFOZIRGOIZHGOURHZ"
      - NEXT_PUBLIC_SITE_URL="http://nextjs:3000"
      - NEXT_PUBLIC_SOCKET_URL=http://nextjs:5157
      
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: satsquare_user
      POSTGRES_PASSWORD: satsquare_password
      POSTGRES_DB: satsquare_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
