# docker-compose.test.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
      - "5157:5157"
    env_file:
      - .env.test

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: sat_square_test_db
    ports:
      - "5432:5432"
