# docker-compose.dev.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5157:5157"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run all-dev

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres_dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: sat_square_dev_db
    ports:
      - "5432:5432"
