---
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 86400
    
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - software-properties-common
        - python3-pip
    
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
    
    - name: Install Docker Compose
      pip:
        name: docker-compose
    