name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      
      - name: Set environment variables
        run: |
               echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" 
